language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - openssl aes-256-cbc -K $encrypted_78aec6180b5a_key -iv $encrypted_78aec6180b5a_iv -in frontend/tools/config.enc -out kc -d
  - ls
  - ./kubectl --kubeconfig=./kc get svc

script:
  - cd frontend/50pm
  - yarn build

after_success:
  - ls build
  - cd ..
  - tools/dockerize.sh