language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - cd frontend
  - openssl aes-256-cbc -K $encrypted_78aec6180b5a_key -iv $encrypted_78aec6180b5a_iv -in tools/config.enc -out kc -d
  - ls
  - kubectl --kubeconfig=./kc get svc

script:
  - cd 50pm
  - yarn build

after_success:
  - ls build
  - cd ..
  - tools/dockerize.sh