language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - cd frontend/50pm

script:
  - pwd
  - ls -R .
  - echo "build done"

after_success:
  - cd ..
  - tools/mk-docker-image.sh