apiVersion: v1
kind: Service
metadata:
  name: fiftypm_api-staging
  labels:
    app: fiftypm_api-staging
spec:
  selector: 
    app: fiftypm_api-staging
  ports:
  - port: 8000
    name: fiftypm_api-staging
  clusterIP: None
